# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\sebcourtois\devspace\cg-pypeline-toolkit\resources\davos\property_editor_view.ui'
#
# Created: Tue Jun 23 13:24:42 2015
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_PropertyEditorView(object):
    def setupUi(self, PropertyEditorView):
        PropertyEditorView.setObjectName("PropertyEditorView")
        PropertyEditorView.resize(800, 264)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PropertyEditorView.sizePolicy().hasHeightForWidth())
        PropertyEditorView.setSizePolicy(sizePolicy)
        PropertyEditorView.setMinimumSize(QtCore.QSize(0, 0))
        PropertyEditorView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.propertyEditorLayout = QtGui.QHBoxLayout(PropertyEditorView)
        self.propertyEditorLayout.setSpacing(4)
        self.propertyEditorLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.propertyEditorLayout.setContentsMargins(2, 4, 2, 2)
        self.propertyEditorLayout.setObjectName("propertyEditorLayout")
        self.imageFrame = QtGui.QFrame(PropertyEditorView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageFrame.sizePolicy().hasHeightForWidth())
        self.imageFrame.setSizePolicy(sizePolicy)
        self.imageFrame.setMinimumSize(QtCore.QSize(258, 258))
        self.imageFrame.setMaximumSize(QtCore.QSize(258, 258))
        self.imageFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.imageFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.imageFrame.setLineWidth(1)
        self.imageFrame.setObjectName("imageFrame")
        self.imageLayout = QtGui.QHBoxLayout(self.imageFrame)
        self.imageLayout.setSpacing(0)
        self.imageLayout.setContentsMargins(0, 0, 0, 0)
        self.imageLayout.setObjectName("imageLayout")
        self.imageButton = ImageButton(self.imageFrame)
        self.imageButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageButton.sizePolicy().hasHeightForWidth())
        self.imageButton.setSizePolicy(sizePolicy)
        self.imageButton.setMinimumSize(QtCore.QSize(0, 0))
        self.imageButton.setMaximumSize(QtCore.QSize(256, 256))
        self.imageButton.setStyleSheet("")
        self.imageButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/icons/CyberLogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.imageButton.setIcon(icon)
        self.imageButton.setIconSize(QtCore.QSize(256, 256))
        self.imageButton.setCheckable(False)
        self.imageButton.setAutoDefault(False)
        self.imageButton.setDefault(False)
        self.imageButton.setFlat(True)
        self.imageButton.setObjectName("imageButton")
        self.imageLayout.addWidget(self.imageButton)
        self.propertyEditorLayout.addWidget(self.imageFrame)
        self.propertiesScrollArea = QtGui.QScrollArea(PropertyEditorView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propertiesScrollArea.sizePolicy().hasHeightForWidth())
        self.propertiesScrollArea.setSizePolicy(sizePolicy)
        self.propertiesScrollArea.setStyleSheet("")
        self.propertiesScrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.propertiesScrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.propertiesScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.propertiesScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.propertiesScrollArea.setWidgetResizable(True)
        self.propertiesScrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.propertiesScrollArea.setObjectName("propertiesScrollArea")
        self.propertiesWidget = QtGui.QWidget()
        self.propertiesWidget.setGeometry(QtCore.QRect(0, 0, 534, 258))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propertiesWidget.sizePolicy().hasHeightForWidth())
        self.propertiesWidget.setSizePolicy(sizePolicy)
        self.propertiesWidget.setMinimumSize(QtCore.QSize(16, 16))
        self.propertiesWidget.setStyleSheet("")
        self.propertiesWidget.setObjectName("propertiesWidget")
        self.propertiesLayout = QtGui.QVBoxLayout(self.propertiesWidget)
        self.propertiesLayout.setSpacing(4)
        self.propertiesLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.propertiesLayout.setContentsMargins(0, 0, 0, 0)
        self.propertiesLayout.setObjectName("propertiesLayout")
        self.propertiesScrollArea.setWidget(self.propertiesWidget)
        self.propertyEditorLayout.addWidget(self.propertiesScrollArea)

        self.retranslateUi(PropertyEditorView)
        QtCore.QMetaObject.connectSlotsByName(PropertyEditorView)

    def retranslateUi(self, PropertyEditorView):
        PropertyEditorView.setWindowTitle(QtGui.QApplication.translate("PropertyEditorView", "Form", None, QtGui.QApplication.UnicodeUTF8))

from pytk.core.widgets import ImageButton
